# Generated by Django 4.1.7 on 2023-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barnes_django', '0002_alter_member_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='regID',
            field=models.CharField(blank=True, default=145, max_length=50),
            preserve_default=False,
        ),
    ]
