# Generated by Django 4.1.7 on 2023-03-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barnes_django', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.IntegerField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
