# Generated by Django 4.1.7 on 2023-03-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Barnes_django', '0005_remove_user_password_user_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
